### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by smcv** [bjarosze/gnome-bluetooth-quick-connect#10]
Thanks for maintaining this extension! I use it frequently for my Bluetooth headphones.

I've added this extension to Debian, under the name `gnome-shell-extension-bluetooth-quick-connect`. It would be helpful for our automated monitoring if you could tag the corresponding commit for each new release with `git tag`, and push those tags to this repository. That would also mean I could use Debian package versions like 8-1 instead of 0~git20190701-1. Ideally, please tag each version that you consider to be ready for general use (the ones you release to extensions.gnome.org), but not intermediate development commits - that way I can make sure to only upload things to Debian when they're ready.

For example, I see extensions.gnome.org currently has version 8 available. If you can tag that version with a command like

    git tag -a -m "gnome-bluetooth-quick-connect v8" v8 abcdef

replacing `abcdef` with the git commit that you used to release version 8, and push that tag, that would be a useful way to keep track.

More information about tagging releases:
* https://git-scm.com/book/en/v2/Git-Basics-Tagging
* https://victoria.dev/verbose/git-commit-practices-your-future-self-will-thank-you-for/#tag-release-versions-using-annotated-git-tags
* https://help.github.com/en/articles/creating-releases (you might not be able to use this method for version 8 if it was older than 355180f1, but you can use it instead of the command-line for future releases if you'd prefer)

**Comment by bjarosze** [comment]
I've added tags for release v7 and v8.

**Comment by smcv** [comment]
Thanks, that looks perfect. I'll base the Debian packaging on tagged releases from now on.
