### ISSUE TITLE
Show bluetooth option also when turned off

### ISSUE THREAD

**Issue by 13hannes11** [bjarosze/gnome-bluetooth-quick-connect#11]
I think it would be a nice addition if the bluetooth menu would be existent even when bluetooth is turned off. This would allow easier activation than going to the settings and enabling it.

**Comment by bjarosze** [comment]
Doesn't it work like that right now?

On this screenshoot I have disabled bluetooth, but I still have bluetooth menu. 
![bluetooth_off](https://user-images.githubusercontent.com/5628088/62768557-604d0880-ba97-11e9-9eef-cf56d367aef7.png)
There is even option in extension that automatically turns on bluetooth when bluetooth menu is opened.

**Comment by 13hannes11** [comment]
Here is how it is for me:
![image](https://user-images.githubusercontent.com/9381167/62953699-44769900-bdee-11e9-96c5-63ae209d63ef.png)

It might be useful to know that I'm using Ubuntu Mate 18.04 (but with Gnome as DE)

**Comment by biswaz** [comment]
Same issue here on ubuntu 18.04

**Comment by bjarosze** [comment]
I believe this is the same issue: #21 

This extension only adds devices to existing menu. It doesn't add bluetooth menu itself or modify it's behavior. Menu is there by default in gnome.

Looks like other people also has this problem: https://askubuntu.com/questions/1203854/ubuntu-18-04-bluetooth-settings-missing-from-upper-right-corner-menu (maybe here you will find some more information).

**Comment by pitlochry** [comment]
It is [fixed](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/1426) in gnome 3.38. Thank you so much for your extension, which is even better after this fix.
