### ISSUE TITLE
Bluetoothctl CLI Note

### ISSUE THREAD

**Issue by keplersj** [bjarosze/gnome-bluetooth-quick-connect#13]
Could we please add a note to the README about ensuring that `bluetoothctl` is installed? I had to install the `bluez-utils` package for this extension to work in my Majaro install. Thankfully this is detailed in the [Arch wiki page on Bluetooth](https://wiki.archlinux.org/index.php/Bluetooth#Installation) if this is exclusive to Arch installs.

**Comment by bjarosze** [comment]
I have added requirements to README.
