### ISSUE TITLE
Please add copyright and license information

### ISSUE THREAD

**Issue by smcv** [bjarosze/gnome-bluetooth-quick-connect#2]
I'd like to package this extension in Debian, but at the moment nobody has permission to redistribute it (except for convenience.js). Please could you add copyright and licensing information? This marks it as fully open source.

I'd be happy to help you to choose a license, and add the necessary licensing information to make the license obvious to Linux distributions and users.

There's some basic information here: https://choosealicense.com/

**Comment by bjarosze** [comment]
Done.

**Comment by smcv** [comment]
Thanks for adding the LICENSE file. However, you haven't actually given anyone permission to distribute this extension under the terms of that license. I can send a merge request to add the necessary headers if you confirm what you intended.

From the git history I assume the only copyright holder (apart from for convenience.js) is Bartosz Jaroszewski. Is that correct?

You added a copy of the GNU General Public License, version 3. Do you intend to allow use of future versions of the GNU GPL that the Free Software Foundation might write in future ("(or any later version)" as suggested in the "How to Apply These Terms to Your New Programs" section), or do you intend to require GPL version 3 only?

Did you intend to allow use of the older version, GPL version 2?

The license of GNOME Shell itself is the GNU General Public License, version 2 or later (meaning we can choose version 2, version 3, or any future version if the FSF writes one). I would personally suggest doing the same for this extension.

**Comment by bjarosze** [comment]
Yes, I am the only copyright holder. I've just copied license from the page you provided in previous post (https://choosealicense.com). I am not familiar with this, so I'll be glad if you create pull request. We can do as you suggested - the same as Gnome Shell.

**Comment by smcv** [comment]
> We can do as you suggested - the same as Gnome Shell.

Thanks, I'll send a PR for this.
