### ISSUE TITLE
Stopped working with update of May 29th

### ISSUE THREAD

**Issue by hkockerbeck** [bjarosze/gnome-bluetooth-quick-connect#22]
Today, a notification informed me about a new version of Bluetooth quick connect. After I updated the extension, it's not working anymore. The line from `journalctl -b /usr/bin/gnome-shell | grep "bluetooth-quick-connect"` that seem relevant to me is (linebreaks by me for better readability):

    Extension "bluetooth-quick-connect@bjarosze.gmail.com" had error: 
    TypeError: GObject.registerClass() used with invalid base class (is PopupSwitchMenuItem)

I'm running Ubuntu 18.04 with Gnome Shell 3.28.4.

**Comment by bjarosze** [comment]
For now I have removed support for old gnome versions, so you will have to install older one (v10).

Later, I will check if there is easy way to support older versions.

**Comment by llopisdon** [comment]
Hello. It is also no longer working under Gnome Shell 3.34.2 Ubuntu 19.10. 

`
JS ERROR: Exception in callback for signal: device-changed: Error: 3 is not a valid value for enumer
                                        _buildRefreshButton@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.g
                                        _init@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/ui.js
                                        _addMenuItem@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.co
                                        _addDevicesToMenu/<@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.g
                                        _addDevicesToMenu@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gma
                                        _refresh@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/ex
                                        _connectControllerSignals/<@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bj
                                        _emit@resource:///org/gnome/gjs/modules/signals.js:135:27
                                        enable/<@/home/don/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/bl
`

**Comment by bjarosze** [comment]
Thanks for report. I've removed 3.32 and 3.34 from supported versions.

**Comment by steffen-stell** [comment]
I had the same issue with Fedora 31 / Gnome 3.34. Are you planning to fix this or will Gnome 3.34 be permanently unsupported?

**Comment by bjarosze** [comment]
I've added support for gnome 3.34.
Lower versions requires too much work, so I won't support it.
