### ISSUE TITLE
Does not work after update to Gnome 3.38

### ISSUE THREAD

**Issue by DestroyerXyz** [bjarosze/gnome-bluetooth-quick-connect#25]

**Comment by gfernandez-me** [comment]
Same here, trying to install on Ubuntu 20, but is not working

when you click to install the button change the label to ERROR

**Comment by DestroyerXyz** [comment]
Works for me now

**Comment by gfernandez-me** [comment]
what did you do? Oo

**Comment by DestroyerXyz** [comment]
Just tried to install it again and it worked

**Comment by gfernandez-me** [comment]
manual installation is working, but not through the chrome!
many thanks
