### ISSUE TITLE
error on fedora 33

### ISSUE THREAD

**Issue by drahnr** [bjarosze/gnome-bluetooth-quick-connect#26]
After updating to fedora 33 version 16 of the extension only shows <kbd>error</kbd> https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/

**Comment by drahnr** [comment]
Note that with `lg` it turns out that one needs to logout and login again, which is not obvious.

**Comment by cinatic** [comment]
probably related to https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/6ddd43f36178939d0e1873a40f1cf66f26c61140
