### ISSUE TITLE
Does no longer work on Ubuntu 20.04.1 LTS / Gnome 3.36.3

### ISSUE THREAD

**Issue by mgmgwi** [bjarosze/gnome-bluetooth-quick-connect#27]
Thanks for the extension, it worked fine on Ubuntu 18.04 but after the update to 20.04 it stopped working. Clicking on the enable/disable switch does nothing anymore. Manually connecting/disconnecting to/from the device via bluetoothctl does work. I reinstalled the dependencies via

```
$ sudo apt purge bluez gnome-bluetooth pulseaudio-module-bluetooth
$ sudo apt install bluez gnome-bluetooth pulseaudio-module-bluetooth
```
and restarted, but it did not help.

The are no errors shown with `journalctl -f`. I enabled _Debug Mode_ in extension settings, but I don't know where to look for the log files.

Thanks for any help!

**Comment by bjarosze** [comment]
Could you try to remove extension and install it manually from github.

Few people reported the same problem and reinstalling helped. I don't know why it is so. I am unable reproduce it.

**Comment by mgmgwi** [comment]
I tried reinstalling, but it did not help. I played around a bit more and I think the problem is that

```
bluetoothctl -- [command]
```

does note work. If I run that from a bash shell, it starts `bluetoothctl` but does not execute the command (e.g. `connect xx:xx:xx.xx`). I can enter the command manually on the bluetoothctl prompt and then it works.

```
> bluetoothctl --version
5.44
> sudo apt list bluez
Listing... Done
bluez/focal,now 5.53-0ubuntu3 amd64 [installed]
bluez/focal 5.53-0ubuntu3 i386
```

Any more ideas?

**Comment by bjarosze** [comment]
It looks that you have old version of bluetoothctl. Apt shows 5.53, but `--version` shows 5.44.
What is the output of: `which bluetoothctl` and `/usr/bin/bluetoothctl --version`? Maybe you have two versions and older one is in your PATH?

**Comment by mgmgwi** [comment]
You are correct :+1: 

I removed the version in `/usr/local/bin/bluetoothctl` and now it's working.

Thank you very much!
