### ISSUE TITLE
ui improvement: disconnect the current connection in the case another device is selected for connecting

### ISSUE THREAD

**Issue by swissiety** [bjarosze/gnome-bluetooth-quick-connect#29]
current situation:
1 device is connected. 2 devices are paired and thus listed in the ui. I want to connect to the unconnected device. To achieve this i need to disconnect before i can connect to the other device.

what I would expect:
disconnect the current connection automatically.

**Comment by daPhipz** [comment]
I totally understand what your problem is, and I would like this feature, too. But making this the default behaviour is not good, I think. At least on Smartphones, you want to be able to connect more than one device at a time (e.g. smartwatch and headphones).

There may be a usecase where this applies to computers as well. Maybe a setting to toggle this behaviour on and off would be the solution?

Merry Christmas, btw 😊🎄

**Comment by swissiety** [comment]
good objection - im not experienced enough whether concurrent connections were generally possible with a single adapter - since it doesnt work on my setup. maybe there is some way to detect if the adapter has the ability for multiple connections, too?

**Comment by egormanga** [comment]
@swissiety All bluetooth controllers should have this functionality afaik, but you need to explicitly allow it in `/etc/bluetooth/main.conf`:
```ini
# Enables Multi Profile Specification support. This allows to specify if
# system supports only Multiple Profiles Single Device (MPSD) configuration
# or both Multiple Profiles Single Device (MPSD) and Multiple Profiles Multiple
# Devices (MPMD) configurations.
# Possible values: "off", "single", "multiple"
MultiProfile = multiple
```
(the default is `off` currently, fsr.)

Here's an example of me using just that (works on all my devices, regardless of type/age/gen of the controller):
<details><summary>Screenshot</summary><br>

![image](https://user-images.githubusercontent.com/19863479/202216869-0cc370f8-79de-4b97-8b49-b18c1fdbc34c.png)

</details>

**Comment by dreua** [comment]
It's nowadays pretty common to have multiple bluetooth devices connected (Mouse, Game Controller, Keyboard, Headphones, Speakers...).
