### ISSUE TITLE
Add support for GNOME 40

### ISSUE THREAD

**Issue by frandieguez** [bjarosze/gnome-bluetooth-quick-connect#30]
**Extension Information**

- Shell Version: GNOME 40
- Extension Version: 16
- Install method: extension.gnome.org
- OS: Fedora 33 with GNOME 40 alfa installed via ```sudo dnf copr enable haeckerfelix/gnome-shell-40 && sudo dnf update```

**Describe the bug**
GNOME 40 is already in alfa and it forces the usage of GTK4 for extensions dialogs.

**More information:**

The extensions seems to work so far but when you try to open the preferences dialog of your awesome extension it crashes with the message below point_down

```
Gtk.BuilderError: /home/fran/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/Settings.ui:19:35 Invalid property: GtkBox.margin_left

Stack trace:
  build@/home/fran/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/prefs.js:23:23
  buildPrefsWidget@/home/fran/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/prefs.js:86:27
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:22
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Please update you extension to keep enjoying using it. Thanks for your incredible work!

**Comment by bjarosze** [comment]
I will adjust it to GNOME 40, but only when I get it. I use Ubuntu, so no sooner than end of April.

**Comment by frandieguez** [comment]
you can alweays use GNOME Boxes with the latest changes 
Check the post at https://blogs.gnome.org/shell-dev/2021/02/01/another-shell-ux-update/

**Comment by bjarosze** [comment]
Done.

**Comment by frandieguez** [comment]
Note that in the metadata.json, the version refers to version 40.0, maybe you need to reference "40", so it will be compatible with "40.1" 40.2"...
