### ISSUE TITLE
Incompatible for Gnome 40.2

### ISSUE THREAD

**Issue by arthurflor23** [bjarosze/gnome-bluetooth-quick-connect#35]
Hi,
Currently, the extension is incompatible for Arch + Gnome 40.2 (I think its just metadata)

![image](https://user-images.githubusercontent.com/11759042/121820745-dc53a100-cc6a-11eb-947a-011bc3df9c02.png)

**Comment by yamatt** [comment]
Just upgraded to Fedora 34, I have a similar thing, it says "Outdated" for me (which seems a bit harsh), but it's roughly the same thing.

**Comment by bjarosze** [comment]
Fixed.
