### ISSUE TITLE
Add an option to attempt to reconnect to the same device at resuming from suspend

### ISSUE THREAD

**Issue by pacho2** [bjarosze/gnome-bluetooth-quick-connect#37]
Hello,

One thing I need to do every time I close the lid of my laptop and suspends is to manually reconnect to the speaker I am connected to every time I resume.

Maybe it would be possible to attempt to reconnect to the devices that were connected at the time that "disable" call was got by the extension due to suspending.

Thanks a lot

**Comment by bjarosze** [comment]
I think it's bluetooth service issue. My devices gets reconnected after suspend.

There are some bugs reports in ubuntu regarding this issue: https://bugs.launchpad.net/ubuntu/+source/bluez/+bug/1883028
