### ISSUE TITLE
[Feature] Include WIFI as well

### ISSUE THREAD

**Issue by mbousq** [bjarosze/gnome-bluetooth-quick-connect#39]
Thank you **so much** for this extension ! 

I am just writing this for potential future work if is interested. It would be very good to reproduce this for wifi and maybe rebrand the extension as wifi/bluetooth quick connect. Just a thought! 

Thanks again

**Comment by bjarosze** [comment]
Sorry, I have very little time, so I don't plan to add new features not related with bluetooth itself.
