### ISSUE TITLE
Incompatible with GNOME 41

### ISSUE THREAD

**Issue by bdaase** [bjarosze/gnome-bluetooth-quick-connect#40]
Just an early heads-up that this extension seems incompatible with GNOME 41 (on Fedora 35).
Whenever I enable the extension I get

```
Aug 20 14:32:25 p14s-gen2-amd gnome-shell[2050]: error: Bluetooth quick connect: Error trying to execute "bluetoothctl"
```

**Comment by azmeuk** [comment]
I can confirm this bug with Archlinux and GNOME 40.4.0

**Comment by bdaase** [comment]
@azmeuk That's interesting because that means it must have regressed from 40.3 to 40.4, as 40.3 was definitely compatible for me.

**Comment by bjarosze** [comment]
I've just upgraded to Fedora 35.
It works fine for me.

Could you run `bluetoothctl -- paired-devices` in terminal? Maybe something here is wrong?

**Comment by bdaase** [comment]
Hmm indeed, now it seems to work again for me. Maybe some other component was broken in an intermediate version?

However, I will close it for now. If it occurs again, I will reopen it.
