### ISSUE TITLE
[UI improvement] Vertically center the device name

### ISSUE THREAD

**Issue by mouncy** [bjarosze/gnome-bluetooth-quick-connect#45]
It's a simple change as you just need to add these 2 lines to the `ui.js` file in the `_init` function.
```
this.label.y_expand = true;
this.label.y_align = Clutter.ActorAlign.CENTER;
```

**Comment by bjarosze** [comment]
What does it change? Could you send screenshot? I see no difference

**Comment by mxsgx** [comment]
Like this

Ubuntu 20.04 LTS

![Device name label is not vertical](https://user-images.githubusercontent.com/45129872/143089402-37327614-f9d8-4927-a5a5-1101ff174f9c.png)

**Comment by bjarosze** [comment]
In Gnome 42 this is set by default for `PopupSwitchMenuItem`. So no changes in extension needed.
