### ISSUE TITLE
TypeError: this._client.get_devices is not a function 

### ISSUE THREAD

**Issue by flomertens** [bjarosze/gnome-bluetooth-quick-connect#56]
I have the following issue when installing the latest version of this extension (version 27) on ubuntu 22.04 (fully upgraded):

JS ERROR: Extension bluetooth-quick-connect@bjarosze.gmail.com: TypeError: this._client.get_devices is not a function
                                                BluetoothController@/home/fmertens/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/bluetooth.js:28:36
                                                BluetoothQuickConnect@/home/fmertens/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/extension.js:35:28
                                                enable@/home/fmertens/.local/share/gnome-shell/extensions/bluetooth-quick-connect@bjarosze.gmail.com/extension.js:217:29
                                                _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:182:32
                                                loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:364:26
                                                _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:620:18
                                                collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
                                                _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:19
                                                _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:626:18
                                                _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:646:14
                                                init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                                _initializeUI@resource:///org/gnome/shell/ui/main.js:293:22
                                                start@resource:///org/gnome/shell/ui/main.js:170:5
                                                @resource:///org/gnome/shell/ui/init.js:6:17

By default gir1.2-gnomebluetooth-1.0 is installed on ubuntu. I tried to install gir1.2-gnomebluetooth-3.0 as well, but that's not enough.

**Comment by hadim** [comment]
Same issue here. I think this is fixed in the repo but the release has not been made yet to the extensions website.

@bjarosze : would you have time to cut a new release?

**Comment by bjarosze** [comment]
Looks like Ubuntu still uses old version od gnome bluetooth API.

I will try to add support for both versions tomorrow.

**Comment by hameema** [comment]
i have the same issue with ubuntu 22.04 (beta)
" this._client.get_devices is not a function "

**Comment by bjarosze** [comment]
:+1: 
I will upload it to extensions.gnome.org soon.

**Comment by hadim** [comment]
I confirm the fix. Thanks @bjarosze

**Comment by hameema** [comment]
thanks very much it worked like a charm
