### ISSUE TITLE
Can you include the "Bluetooth battery indicator" extension?

### ISSUE THREAD

**Issue by onlyreportingissues** [bjarosze/gnome-bluetooth-quick-connect#60]
Hi there,

I really like this extension. Can it be included in Bluetooth Quick Connect as an extra option? Would be really cool.

The extension: https://extensions.gnome.org/extension/3991/bluetooth-battery/

Edit: Added the correct link.

**Comment by bjarosze** [comment]
Battery level was added some time ago. It requires bluetooth service to be started with experimental features enabled. More details here: https://github.com/bjarosze/gnome-bluetooth-quick-connect/pull/42
