### ISSUE TITLE
Not compatible with Gnome 44

### ISSUE THREAD

**Issue by pgdooley** [bjarosze/gnome-bluetooth-quick-connect#80]
Gnome 44 is starting to roll out in the latest Ubuntu development release (23.04) - can this be updated to be compatible?

**Comment by netlore** [comment]
Gnome 44 does have a UI that's much more similar to this extension, but it's still lacking the ability to select a device while bluetooth is off.  Combine that with the ability to turn off the bluetooth after a period of inactivity, and I think this extension still has utility even in Gnome 44.

It's also worth noting that if you manually update the manifest.json file to make it load on Gnome 44, it seems function correctly, with just some cosmetic issues.

**Comment by ionutbortis** [comment]
+1 for updating this to Gnome 44

**Comment by dreua** [comment]
I'm rolling with the Gnome built in version for now but its always good to have a choice! (I liked this plugin better in some regards but I'm also lazy.)

Note that Gnome displays the battery levels in the Settigns's "Power" section along with your laptops battery.

**Comment by bjarosze** [comment]
I've adapted it to Gnome 44
